[settings]
timeout = 1000

[relaychain]
default_image = "{{SYNTHIMAGE}}"
chain = "polkadot-local"
command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  extra_args = [ "--alice", "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  command = "/usr/local/bin/malus back-garbage-candidate"
  extra_args = ["--bob", "-lparachain=debug"]
  image = "{{MALUSIMAGE}}"
  autoConnectApi = false


  [[relaychain.nodes]]
  name = "charlie"
  validator = true
  command = "/usr/local/bin/malus back-garbage-candidate"
  extra_args = ["--charlie", "-lparachain=debug"]
  image = "{{MALUSIMAGE}}"
  autoConnectApi = false


  [[relaychain.nodes]]
  name = "david"
  validator = true
  command = "/usr/local/bin/malus back-garbage-candidate"
  extra_args = ["--dave", "-lparachain=debug"]
  image = "{{MALUSIMAGE}}"
  autoConnectApi = false

  [[relaychain.nodes]]
  name = "eve"
  validator = true
    command = "/usr/local/bin/malus suggest-garbage-candidate"
  extra_args = ["--eve", "-lparachain=debug"]
  image = "{{MALUSIMAGE}}"
  autoConnectApi = false

[[parachains]]
id = 100

  [parachains.collator]
  name = "collator01"
  image = "{{COLIMAGE}}"
  command = "/usr/local/bin/adder-collator"
  args = ["-lparachain=debug"]