[settings]
timeout = 1000

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "polkadot-local"
command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  extra_args = [ "--alice", "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  command = "/usr/local/bin/malus back-garbage-candidate"
  extra_args = ["--bob", "-lparachain=debug"]
  image = "{{MALUS_IMAGE}}"


  [[relaychain.nodes]]
  name = "charlie"
  validator = true
  command = "/usr/local/bin/malus back-garbage-candidate"
  extra_args = ["--charlie", "-lparachain=debug"]
  image = "{{MALUS_IMAGE}}"


  [[relaychain.nodes]]
  name = "david"
  validator = true
  command = "/usr/local/bin/malus suggest-garbage-candidate"
  extra_args = ["--dave", "-lparachain=debug"]
  image = "{{MALUS_IMAGE}}"

 [[relaychain.nodes]]
 name = "eve"
 validator = true
 command = "/usr/local/bin/malus suggest-garbage-candidate"
 extra_args = ["--eve", "-lparachain=debug"]
 image = "{{MALUS_IMAGE}}"


[[parachains]]
id = 100

  [parachains.collator]
  name = "collator01"
  image = "{{COL_IMAGE}}"
  command = "/usr/local/bin/adder-collator"
  args = ["-lparachain=debug"]
